---
abstract: 'Command to list dependencies in a Mojolicious project'
author:
  - 'Paul Durden <AlabamaPaul@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-listdeps
requires:
  Cwd: 0
  File::Find: 0
  File::Spec: 0
  Module::CoreList: 0
  Module::Info: 0
  Mojo::Base: 0
  Mojolicious: 3.16
  PPI: 0
  strict: 0
  warnings: 0
version: 0.05
